### ISSUE TITLE
Allow option of downloading JSON or XML files only

### ISSUE THREAD

**Issue by chris-gillatt** [stevespringett/nist-data-mirror#11]
To cut down download sizes and to speed up download times, please could the ability to download JSON or XML files only be added?

**Comment by stevespringett** [comment]
Good suggestion.

**Comment by stevespringett** [comment]
Implemented by #12

**Comment by stevespringett** [comment]
Thanks for the suggestion and implementation. v1.2.0 has just been released to Maven Central with these changes.
