### ISSUE TITLE
NistDataMirror.java has hardcoded Windows file separators

### ISSUE THREAD

**Issue by dwaynewilliams** [stevespringett/nist-data-mirror#111]
Lines 289 and 293 have hardcoded Windows file separators that are causing dependency check jobs to fail on OSX and Linux environments.

**Comment by dwaynewilliams** [comment]
The bug was introduced 8 days ago in this PR - https://github.com/stevespringett/nist-data-mirror/pull/108/files

**Comment by falco9** [comment]
Removed the file seperators & created PR
