### ISSUE TITLE
Unable to build with IBM Java 8

### ISSUE THREAD

**Issue by bartleyj** [stevespringett/nist-data-mirror#118]
I get the following error when I try to build this project locally with IBM Java 8

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project nist-data-mirror: Compilation failure
[ERROR] /tmp/nist-data-mirror/src/main/java/us/springett/nistdatamirror/NistDataMirror.java:[19,52] package com.sun.org.apache.xpath.internal.operations does not exist

I can work around it by removing the unused import of com.sun.org.apache.xpath.internal.operations.Bool in the NistDataMirror.java file.  Since it's not actually used, I would think it could simply be removed in the main codebase and then the project would again be compilable with any jdk.

**Comment by sellersj** [comment]
Removed in 
https://github.com/stevespringett/nist-data-mirror/commit/49ca3d2879fcb8231d43c82f0e555d88682b4fd0

I think that this issue can be closed.

**Comment by bartleyj** [comment]
It can, indeed.  I've confirmed that I can build again with IBM Java without having to apply any local workaround.  Thank you.
