### ISSUE TITLE
Realease of recent NVD Metadata Changes

### ISSUE THREAD

**Issue by albuch** [stevespringett/nist-data-mirror#19]
Could you consider in preparation for DependencyCheck v5.0.0 release to prepare a relase of nist-data-mirror as well?
https://github.com/stevespringett/nist-data-mirror/pull/16

**Comment by stevespringett** [comment]
Jeremy made some changes recently. Have you tested them with m2 by change?

**Comment by albuch** [comment]
If you release the snapshot to Nexus I can give it a try.

**Comment by jeremylong** [comment]
@stevespringett yes - I have tested this with ODC 5.0.0-M3 and the nearly complete ODC 5.0.0-SNAPSHOT.

**Comment by stevespringett** [comment]
Pushed to Maven Central and Docker Hub
