### ISSUE TITLE
entry.sh creates faulty httpd.conf

### ISSUE THREAD

**Issue by Zohhak** [stevespringett/nist-data-mirror#28]
On the startup of the container the entry.sh tries to replace the default port 80 with the internal used port 8080. On restart it tries to do that again and breaks the config by doing so.
At the Moment on second startup the 'Listen' line is 'Listen 808080'

I think the sed command should be changed to:
sed -i 's/^Listen 80$/Listen 8080/g' /usr/local/apache2/conf/httpd.conf

**Comment by stevespringett** [comment]
This is resolved in v1.4.0

**Comment by 0x7d7b** [comment]
@Zohhak This should have been fixed with #40 .
