### ISSUE TITLE
Docker image appears to have been pushed

### ISSUE THREAD

**Issue by camelpunch** [stevespringett/nist-data-mirror#30]
Is this reliable?

https://hub.docker.com/r/sspringett/nvdmirror

**Comment by stevespringett** [comment]
Reliable? That is the latest Docker image that I pushed awhile ago. I personally don't use it, so cannot comment on how reliable it is, but it is the official image from this project. You can of course, use the Dockerfile and build your own container if you wish.

**Comment by camelpunch** [comment]
Cool, I've created a README PR, as I think the README may be out of date: https://github.com/stevespringett/nist-data-mirror/pull/31
