### ISSUE TITLE
Cron not running in Docker container

### ISSUE THREAD

**Issue by g17** [stevespringett/nist-data-mirror#40]
After building the Docker container and starting it as described in the readme the log prints the following line which states that the mirror crontab setting is being ignored:

`Oct  1 08:27:54 nist-data-mirror.somewhere.net crond: ignoring /etc/crontabs/mirror (non-existent user)`

**Comment by httran13** [comment]
After the merge, i am no longer able to reach the service(I was able to before but was getting a 403)

`[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.2.2:aggregate (default) on project ucs-filemonitor-service: Fatal exception(s) analyzing FileMonitor: One or more exceptions occurred during analysis:
[ERROR]         Unable to download meta file: http://localhost/nvdcve-1.0-modified.meta
[ERROR]         No documents exist
[ERROR] -> [Help 1]
[ERROR] 
`

**Comment by stevespringett** [comment]
Released in v1.4.0
