### ISSUE TITLE
Insufficient validation of proxy settings

### ISSUE THREAD

**Issue by g17** [stevespringett/nist-data-mirror#41]
The check for proxy system properties is not sufficient. There should not only be a `null` check but also a check for empty strings:

https://github.com/stevespringett/nist-data-mirror/blob/5e5ef4ad779d74820bdd250d0dc00c691128e4e2/src/main/java/us/springett/nistdatamirror/NistDataMirror.java#L96

 This is because in the `mirror.sh` script which is executed in the Docker environment the proxy properties are always being set. In case no `proxy_host`or `proxy_port` environment variable is set the `http.proxyHost` or `http.proxyPort` JVM properties are set to an empty string:

https://github.com/stevespringett/nist-data-mirror/blob/5e5ef4ad779d74820bdd250d0dc00c691128e4e2/src/docker/scripts/mirror.sh#L3

**Comment by stevespringett** [comment]
Released in v1.4.0
