### ISSUE TITLE
release 1.4.0 compiled against newer jdk

### ISSUE THREAD

**Issue by dnozay** [stevespringett/nist-data-mirror#56]
```
11:11:27  Exception in thread "main" java.lang.UnsupportedClassVersionError: us/springett/nistdatamirror/NistDataMirror : Unsupported major.minor version 52.0
11:11:27  	at java.lang.ClassLoader.defineClass1(Native Method)
11:11:27  	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
11:11:27  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
11:11:27  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
11:11:27  	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
11:11:27  	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
11:11:27  	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
11:11:27  	at java.security.AccessController.doPrivileged(Native Method)
11:11:27  	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
11:11:27  	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
11:11:27  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
11:11:27  	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
11:11:27  	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)```
```

Hello,
OpenJDK7 is still supported until June 2020
https://access.redhat.com/articles/1299013
Would you mind releasing a jar that still works with 1.7 ?

Thank you

**Comment by stevespringett** [comment]
Historically, this project was compiled against Oracle JDK, which in version 7, was EOL in 2015. Oracle JDK was necessary as OpenJDK (at the time) used slightly different certificate trust stores making TLS handshaking with the NVD impossible. TLS v1.2 support was also disabled in Java 7 at the time. 

It would be a bit of a research project with some trial and error to figure out if it will work with Java 7, which is not something I have time or interest in doing. 

I'd recommend forking the project, making any necessary changes to support Java 7. Also keep in mind that this project isn't doing anything special that cannot easily be done with curl and a simple shell script.

**Comment by dnozay** [comment]
thanks for the update
