### ISSUE TITLE
Release the binary

### ISSUE THREAD

**Issue by bdellegrazie** [stevespringett/nist-data-mirror#6]
Hi

Is there any possibility of releasing this as a binary to bintray or github releases?
Just FYI, bintray has free releases for open source projects and is a good way of getting JARs / WARs etc. into maven central (this is optional).

Thanks!

**Comment by stevespringett** [comment]
great idea. I've pushed the 1.1.0 release to GitHub releases as well as Maven Central. Central will take several hours to replicate but should be available tomorrow. I've also update the readme to make these options known

**Comment by bdellegrazie** [comment]
Thanks very much :)
