### ISSUE TITLE
HELM Chart - Allow http proxy values to be supplied through values.yaml.

### ISSUE THREAD

**Issue by mookkiah** [stevespringett/nist-data-mirror#62]
The mirror script uses below command which takes http proxy host and port. But the HELM template is not providing option to supply these environment variables.

```
java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -jar -Dhttp.proxyHost="${proxy_host}" -Dhttp.proxyPort="${proxy_port}" /usr/local/bin/nist-data-mirror.jar /tmp/nvd
```

Please allow these values to be supplied through values.yaml. It would be good if we even add additional env variables if consumer needed it.

**Comment by mookkiah** [comment]
we are going to try following options before deciding we need change in the chart.

1. Try setting environment variable http_proxy and https_proxy.
2. Try setting JAVA_OPTS environment variable with -Dhttp.proxyHost and -Dhttp.proxyPort 
3. Try setting JAVA_TOOL_OPTIONS with -Dhttp.proxyHost and -Dhttp.proxyPort

**Comment by stevespringett** [comment]
v1.5.1 released.
