### ISSUE TITLE
json 1.0 feeds no longer supported?

### ISSUE THREAD

**Issue by oosterholt** [stevespringett/nist-data-mirror#68]
It looks like the json 1.0 feeds are no longer supported. This was announced [here](https://nvd.nist.gov/General/News/JSON-1-1-Vulnerability-Feed-Release).
Looks like they finally decided to take the old feeds offline.
Since nist-data-mirror tries to download both versions, an error level is reported once it has finished.

**Comment by sellersj** [comment]
Thank you for opening a
ticket https://github.com/stevespringett/nist-data-mirror/issues/68

Jim

**Comment by rcooper85** [comment]
Is it as simple as removing the reference to 1.0 in the main method? I tested it locally and it seemed to work for me. 
![image](https://user-images.githubusercontent.com/20299737/93602964-47619700-f9bb-11ea-809d-59932b055800.png)

**Comment by stevespringett** [comment]
Resolved in 1.5.0

**Comment by albuch** [comment]
Hi @stevespringett 
could you please release the 1.5.0 tag? It's not yet available at Maven Central:
https://search.maven.org/artifact/us.springett/nist-data-mirror

**Comment by stevespringett** [comment]
Ah - Forgot to hit release on central. Done.
