### ISSUE TITLE
NVD mirror to dependency check 

### ISSUE THREAD

**Issue by ammy1999** [stevespringett/nist-data-mirror#9]
Hello, 
Usually I have this error  : Fatal exception(s) analyzing Core RH: Unable to continue dependency-check analysis.
[ERROR] Unable to connect to the database
So I think to mirrir the CPE/CVE to have local access 
But I don't unterstand how can I add it ! help please 
(what is the utility of the database H2 in dependency check , ii contain just the CVE to check the vulnerability ?? )

**Comment by ammy1999** [comment]
java -jar nist-data-mirror.jar <mirror-directory> what's mean <mirror-directory> !! help please

**Comment by stevespringett** [comment]
nist-data-mirror is only required if you want to create a duplicate data feed of the NVD inside a corporate firewall. This is completely optional and not required by Dependency-Check. This project has no affect on Dependency-Checks ability to connect to the database.

**Comment by ammy1999** [comment]
Thanks @stevespringett  but  what's mean corporate firewall please, Can I unterstand the mecanism to utilize the database H2 and the NVD ??

**Comment by stevespringett** [comment]
This project does not use a database. It mirrors files from the NVD to your local filesystem.

**Comment by ammy1999** [comment]
this project you mean dependency check !! because when I check the code source , it utilize H2 database (contains the CVE )

**Comment by stevespringett** [comment]
This isn't the dependency-check project. This is the nist-data-mirror project which can optionally be used with dependency-check.
